spring.profiles.active=${EQUIPMENT_ACTIVE_PROFILE:local}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EQUIPMENT_MAIL_USER:dummy@gmail.com}
spring.mail.password=${EQUIPMENT_MAIL_PASSWORD:dummy}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

