spring.datasource.url=jdbc:mysql://equipment3-rds-2.cfl3bk5opxfy.ap-northeast-1.rds.amazonaws.com:3306/equipment_management?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=${EQUIPMENT_DB_PASSWORD}
cors.allowed.origins=http://54.238.163.86
