name: CI/Checkstyle

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run check style
        uses: nikitasavinov/checkstyle-action@master
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-pr-check'
          tool_name: 'reviewdog'
          checkstyle_config: 'config/checkstyle/checkstyle.xml'
          workdir: 'src/main'
          level: error

      - name: Docker run
        run: docker compose up -d

      - name: Test with Gradle
        run: ./gradlew test
        if: always()

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          job_name: 'Test Report'

      - name: Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "Checkstyle"
          url: "https://github.com/sarisia/actions-status-discord"
          username: GitHub Actions
